-- DDL for ComposedAnnotationSpec (H2 Database)

CREATE TABLE IF NOT EXISTS USERS (
    ID INTEGER PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP NOT NULL
);
