-- DDL for CustomQueryValidationSpec (H2 Database)

CREATE TABLE TABLE1 (
    ID INTEGER PRIMARY KEY,
    COLUMN1 INTEGER NOT NULL,
    COLUMN2 DATE NOT NULL,
    COLUMN3 DECIMAL(10, 2) NOT NULL,
    COLUMN4 VARCHAR(50) NOT NULL
);

CREATE TABLE CATEGORIES (
    ID INTEGER PRIMARY KEY,
    NAME VARCHAR(50) NOT NULL
);
