-- DDL for ProgrammaticPreparationApiSpec (H2 Database)

CREATE TABLE IF NOT EXISTS USERS (
    ID INTEGER PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(200)
);

CREATE TABLE IF NOT EXISTS ORDERS (
    ID INTEGER PRIMARY KEY,
    USER_ID INTEGER NOT NULL,
    PRODUCT VARCHAR(100) NOT NULL,
    AMOUNT DECIMAL(10, 2) NOT NULL,
    FOREIGN KEY (USER_ID) REFERENCES USERS(ID)
)
