-- DDL for DataFormatTest
-- Tests CSV, TSV, JSON, YAML, and AUTO data format loading

CREATE TABLE IF NOT EXISTS DATA_FORMAT (
    ID INTEGER PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    DATA_VALUE INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS DATA_FORMAT_CSV (
    ID INTEGER PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS DATA_FORMAT_JSON (
    ID INTEGER PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL
);
