-- Schema for CONFIG_ITEMS table used in PropertiesConfigurationTest
CREATE TABLE IF NOT EXISTS CONFIG_ITEMS (
    ID BIGINT PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    STATUS VARCHAR(50) NOT NULL,
    CREATED_DATE DATE NOT NULL
);
